# Generated by Django 5.2.8 on 2025-12-02 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achievement_type', models.CharField(choices=[('first_win', 'First Victory'), ('tournament_champion', 'Tournament Champion'), ('undefeated', 'Undefeated Champion'), ('comeback', 'Comeback Kings'), ('dynasty', 'Dynasty'), ('win_streak', 'Win Streak'), ('perfect_season', 'Perfect Season'), ('giant_slayer', 'Giant Slayer'), ('getting_started', 'Getting Started'), ('experienced', 'Experienced'), ('veterans', 'Veterans'), ('legends', 'Legends'), ('full_roster', 'Full Roster')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon identifier or emoji', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Achievement-specific data')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='teams.team')),
            ],
            options={
                'db_table': 'team_achievements',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['team', '-earned_at'], name='team_achiev_team_id_411389_idx'), models.Index(fields=['achievement_type'], name='team_achiev_achieve_fd41ad_idx')],
                'unique_together': {('team', 'achievement_type', 'metadata')},
            },
        ),
        migrations.CreateModel(
            name='TeamAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_announcements', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='teams.team')),
            ],
            options={
                'db_table': 'team_announcements',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='team_announ_team_id_52dcea_idx'), models.Index(fields=['team', 'is_pinned'], name='team_announ_team_id_28e482_idx')],
            },
        ),
    ]
