# Generated by Django 5.2.8 on 2026-02-08 21:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem_cart_store_cart_user_id_3a541e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Unique order number (e.g., EYT-2024-001234)', max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of all item prices before shipping and tax', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total amount (subtotal + shipping + tax)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_name', models.CharField(max_length=200)),
                ('shipping_address_line1', models.CharField(max_length=200)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=200)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current order status', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=100)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack')], help_text='Payment method used (Stripe or Paystack)', max_length=20)),
                ('payment_intent_id', models.CharField(help_text='Payment gateway transaction ID', max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Product name at time of purchase', max_length=200)),
                ('variant_name', models.CharField(blank=True, help_text='Variant name at time of purchase', max_length=100)),
                ('quantity', models.IntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (unit_price × quantity)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(help_text='Reference to the product (preserved even if product is deleted)', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional product variant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='store_order_user_id_f28375_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='store_order_order_n_317f52_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='store_order_status_428b25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='store_order_created_cad692_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_intent_id'], name='store_order_payment_c67b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='store_order_product_056298_idx'),
        ),
    ]
