# Generated by Django 5.2.8 on 2026-02-09 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('unsubscribe_token', models.CharField(help_text='Unique token for unsubscribe link', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='store_newsl_email_d4607b_idx'), models.Index(fields=['is_active'], name='store_newsl_is_acti_3b6f6e_idx'), models.Index(fields=['unsubscribe_token'], name='store_newsl_unsubsc_a30a77_idx')],
            },
        ),
    ]
