# Generated by Django 5.2.8 on 2026-03-18 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order in which the product was purchased (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.order'),
        ),
    ]
