# Generated by Django 5.2.8 on 2025-11-24 10:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('fighting', 'Fighting'), ('fps', 'First-Person Shooter'), ('moba', 'MOBA'), ('sports', 'Sports'), ('racing', 'Racing'), ('strategy', 'Strategy'), ('battle_royale', 'Battle Royale'), ('other', 'Other')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='games/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='games/banners/')),
                ('developer', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('official_website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_teams', models.BooleanField(default=False)),
                ('min_team_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_team_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EYTGaming', max_length=100)),
                ('site_tagline', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(max_length=254)),
                ('discord_server', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('twitch_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('registrations_open', models.BooleanField(default=True)),
                ('tournaments_enabled', models.BooleanField(default=True)),
                ('coaching_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('steam_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('twitch_username', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('player', 'Player'), ('coach', 'Coach/Tutor'), ('organizer', 'Tournament Organizer'), ('admin', 'Administrator'), ('parent', 'Parent/Guardian')], default='player', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_minor', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('parent_email', models.EmailField(blank=True, help_text='Required for users under 18', max_length=254)),
                ('parental_consent', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('private_profile', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_game_name', models.CharField(max_length=100)),
                ('skill_rating', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('tournaments_participated', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('preferred_role', models.CharField(blank=True, max_length=50)),
                ('is_main_game', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game Profile',
                'verbose_name_plural': 'User Game Profiles',
                'db_table': 'user_game_profiles',
                'ordering': ['-is_main_game', '-skill_rating'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='users_usernam_b4c624_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usergameprofile',
            unique_together={('user', 'game')},
        ),
    ]
