# Generated by Django 5.2.8 on 2025-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_account_locked_user_account_locked_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='user',
            name='online_status_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='statistics_visible',
            field=models.BooleanField(default=True),
        ),
    ]
