# Generated by Django 5.2.8 on 2025-12-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_profile_dashboard_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usergameprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_game', True)), fields=('user',), name='unique_main_game_per_user'),
        ),
    ]
