# Generated by Django 5.2.8 on 2025-12-29 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_main_game_uniqueness_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameprofile',
            name='mmr',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usergameprofile',
            name='in_game_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
