# Generated by Django 5.2.8 on 2026-02-08 00:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Product image', upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False, help_text='Show on landing page')),
                ('display_order', models.IntegerField(default=0, help_text='Order in showcase (lower = first)')),
                ('is_available', models.BooleanField(default=True, help_text='Product is in stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'landing_products',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_featured', 'display_order'], name='landing_pro_is_feat_bb76dc_idx'), models.Index(fields=['is_available'], name='landing_pro_is_avai_46cd64_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for cards', max_length=300)),
                ('content', models.TextField(help_text='Full article content')),
                ('image', models.ImageField(help_text='Featured image', upload_to='news/')),
                ('category', models.CharField(choices=[('tournament', 'Tournament'), ('announcement', 'Announcement'), ('update', 'Update'), ('community', 'Community'), ('esports', 'Esports')], default='announcement', max_length=20)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'db_table': 'landing_news_articles',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['is_published', '-published_date'], name='landing_new_is_publ_2d3eb8_idx'), models.Index(fields=['category', '-published_date'], name='landing_new_categor_740dd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gamer_tag', models.CharField(help_text="Player's gaming name", max_length=100, unique=True)),
                ('role', models.CharField(help_text="Player role (e.g., 'Mid Laner', 'Entry Fragger')", max_length=100)),
                ('country_flag', models.CharField(help_text="Country flag emoji or code (e.g., '🇺🇸' or 'US')", max_length=10)),
                ('image', models.ImageField(help_text='Player profile image', upload_to='players/')),
                ('kd_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Kill/Death ratio', max_digits=5)),
                ('rank', models.CharField(help_text="Player rank (e.g., 'Radiant', 'Global Elite')", max_length=50)),
                ('wins', models.IntegerField(default=0, help_text='Total wins', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False, help_text='Display on landing page')),
                ('display_order', models.IntegerField(default=0, help_text='Order in showcase (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_players', to='core.game')),
            ],
            options={
                'verbose_name': 'Featured Player',
                'verbose_name_plural': 'Featured Players',
                'db_table': 'landing_players',
                'ordering': ['display_order', '-kd_ratio'],
                'indexes': [models.Index(fields=['is_featured', 'display_order'], name='landing_pla_is_feat_b3c4ee_idx'), models.Index(fields=['game', 'is_featured'], name='landing_pla_game_id_a35dde_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='videos/thumbnails/')),
                ('video_url', models.URLField(help_text='YouTube, Twitch, or direct video URL')),
                ('duration', models.DurationField(help_text='Video duration')),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured video')),
                ('is_published', models.BooleanField(default=True, help_text='Make visible on site')),
                ('display_order', models.IntegerField(default=0, help_text='Order in list (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.game')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'landing_videos',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['is_published', 'is_featured'], name='landing_vid_is_publ_1b9a00_idx'), models.Index(fields=['-published_date'], name='landing_vid_publish_43d4e9_idx')],
            },
        ),
    ]
