# Generated by Django 5.2.8 on 2026-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_gender_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_grace_started_at',
            field=models.DateTimeField(blank=True, help_text='When the 2FA grace period started (null = not started yet)', null=True),
        ),
    ]
