# Generated by Django 5.2.3 on 2026-06-14 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_user_presence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('celebrity', 'Celebrity')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='celebrity_bio',
            field=models.TextField(blank=True, help_text='Extended bio shown on celebrity profile', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_personality',
            field=models.BooleanField(default=False, help_text='Blue checkmark — manually verified personality'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_team_slots',
            field=models.IntegerField(default=1, help_text='Max teams user can own/captain (5 for celebrities)'),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsorship_email',
            field=models.EmailField(blank=True, help_text='Business inquiries email', max_length=254),
        ),
        migrations.CreateModel(
            name='PersonalityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='{"twitch": "...", "youtube": "...", "twitter": "..."}')),
                ('follower_counts', models.JSONField(blank=True, default=dict, help_text='{"twitch": 50000, "youtube": 200000}')),
                ('additional_info', models.TextField(blank=True, help_text='Why you should be verified', max_length=2000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personality Verification',
                'verbose_name_plural': 'Personality Verifications',
                'db_table': 'personality_verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
