# Generated by Django 5.2.8 on 2025-11-24 10:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bracket_type', models.CharField(choices=[('main', 'Main Bracket'), ('losers', 'Losers Bracket'), ('groups', 'Group Stage'), ('finals', 'Finals')], default='main', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('total_rounds', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tournament_brackets',
                'ordering': ['tournament', 'bracket_type'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField(help_text='Position within round')),
                ('score_p1', models.IntegerField(default=0)),
                ('score_p2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Start'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_grand_finals', models.BooleanField(default=False)),
                ('bracket_reset', models.BooleanField(default=False, help_text='Double elim grand finals reset')),
                ('notes', models.TextField(blank=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.bracket')),
                ('next_match_loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_loser_matches', to='tournaments.match')),
                ('next_match_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_winner_matches', to='tournaments.match')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'db_table': 'tournament_matches',
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='MatchDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='disputes/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tournaments.match')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], default='confirmed', max_length=20)),
                ('seed', models.IntegerField(blank=True, help_text='Seeding position', null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('final_placement', models.IntegerField(blank=True, null=True)),
                ('prize_won', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='teams.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournament_participants',
                'ordering': ['seed', 'registered_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='tournaments.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='participant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='tournaments.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='tournaments.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.participant'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True, help_text='Tournament specific rules')),
                ('format', models.CharField(choices=[('single_elim', 'Single Elimination'), ('double_elim', 'Double Elimination'), ('swiss', 'Swiss System'), ('round_robin', 'Round Robin'), ('group_stage', 'Group Stage + Playoffs')], default='single_elim', max_length=20)),
                ('tournament_type', models.CharField(choices=[('online', 'Online'), ('local', 'Local/Venue'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration Open'), ('check_in', 'Check-in Period'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_team_based', models.BooleanField(default=False)),
                ('min_participants', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)])),
                ('max_participants', models.IntegerField(default=32, validators=[django.core.validators.MinValueValidator(2)])),
                ('team_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('requires_approval', models.BooleanField(default=False)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('check_in_start', models.DateTimeField(help_text='When check-in opens')),
                ('start_datetime', models.DateTimeField(help_text='Tournament start time')),
                ('estimated_end', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prize_distribution', models.JSONField(blank=True, default=dict, help_text="e.g., {'1st': 50, '2nd': 30, '3rd': 20}")),
                ('seeding_method', models.CharField(choices=[('random', 'Random'), ('skill', 'Skill-based'), ('manual', 'Manual'), ('registration', 'Registration Order')], default='random', max_length=20)),
                ('best_of', models.IntegerField(default=1, help_text='Best of X games per match', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournaments/banners/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tournaments/thumbnails/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_verification', models.BooleanField(default=False, help_text='Only verified users can join')),
                ('skill_requirement', models.CharField(blank=True, help_text='Minimum skill level required', max_length=20)),
                ('stream_url', models.URLField(blank=True, help_text='Twitch/YouTube stream link')),
                ('discord_invite', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_registered', models.IntegerField(default=0)),
                ('total_checked_in', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='core.game')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
