# Generated by Django 5.2.8 on 2025-11-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', '-start_datetime'], name='tournaments_status_38c089_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['game', 'status'], name='tournaments_game_id_ce3738_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_public', 'is_featured'], name='tournaments_is_publ_2863ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('tournament', 'team'), ('tournament', 'user')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_9dcd31_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['bracket', 'round_number'], name='tournament__bracket_9f63a0_idx'),
        ),
    ]
