# Generated by Django 5.2.8 on 2025-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_webhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], default='confirmed', max_length=20),
        ),
    ]
