# Generated by Django 5.2.8 on 2025-12-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_add_pending_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description', max_length=160),
        ),
        migrations.AddField(
            model_name='tournament',
            name='primary_color',
            field=models.CharField(default='#b91c1c', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='secondary_color',
            field=models.CharField(default='#111827', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/social/'),
        ),
    ]
