# Generated by Django 5.2.8 on 2025-12-20 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_add_enhanced_tournament_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('discord', 'Discord'), ('direct', 'Direct Link'), ('facebook', 'Facebook')], max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_shares',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['tournament', 'platform'], name='tournament__tournam_df0f47_idx'), models.Index(fields=['shared_at'], name='tournament__shared__eb73c0_idx')],
            },
        ),
    ]
