# Generated by Django 5.2.8 on 2025-12-22 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tournaments', '0009_add_match_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('avg_load_time', models.FloatField(blank=True, null=True)),
                ('avg_time_on_page', models.FloatField(blank=True, null=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('avg_scroll_depth', models.FloatField(blank=True, null=True)),
                ('bounce_rate', models.FloatField(blank=True, null=True)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('avg_first_paint', models.FloatField(blank=True, null=True)),
                ('avg_largest_contentful_paint', models.FloatField(blank=True, null=True)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('mobile_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_summary',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', '-period_start'], name='analytics_s_period__5255c6_idx'), models.Index(fields=['-period_start'], name='analytics_s_period__7294f6_idx')],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('page_type', models.CharField(default='tournament_detail', max_length=50)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('load_time', models.PositiveIntegerField(blank=True, help_text='Total page load time in ms', null=True)),
                ('dom_content_loaded', models.PositiveIntegerField(blank=True, help_text='DOM content loaded time in ms', null=True)),
                ('first_paint', models.PositiveIntegerField(blank=True, help_text='First paint time in ms', null=True)),
                ('first_contentful_paint', models.PositiveIntegerField(blank=True, help_text='First contentful paint time in ms', null=True)),
                ('largest_contentful_paint', models.PositiveIntegerField(blank=True, help_text='Largest contentful paint time in ms', null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_page_views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(choices=[('javascript', 'JavaScript Error'), ('network', 'Network Error'), ('performance', 'Performance Issue'), ('accessibility', 'Accessibility Issue')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('column_number', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.pageview')),
            ],
            options={
                'db_table': 'analytics_error_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registration_started', 'Registration Started'), ('registration_completed', 'Registration Completed'), ('payment_started', 'Payment Started'), ('payment_completed', 'Payment Completed'), ('share_completed', 'Share Completed'), ('email_signup', 'Email Signup')], max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('referrer_url', models.URLField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.pageview')),
            ],
            options={
                'db_table': 'analytics_conversion_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('core_web_vitals', 'Core Web Vitals'), ('resource_timing', 'Resource Timing'), ('user_timing', 'User Timing'), ('navigation_timing', 'Navigation Timing')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(default='ms', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('is_mobile', models.BooleanField(default=False)),
                ('connection_type', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='tournaments.pageview')),
            ],
            options={
                'db_table': 'analytics_performance_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='Time spent on page in seconds', null=True)),
                ('scroll_depth', models.PositiveIntegerField(default=0, help_text='Maximum scroll depth as percentage (0-100)')),
                ('clicks_count', models.PositiveIntegerField(default=0, help_text='Total number of clicks')),
                ('registration_button_clicks', models.PositiveIntegerField(default=0)),
                ('share_button_clicks', models.PositiveIntegerField(default=0)),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('participant_card_clicks', models.PositiveIntegerField(default=0)),
                ('bracket_preview_clicks', models.PositiveIntegerField(default=0)),
                ('bounced', models.BooleanField(default=False, help_text='User left without meaningful interaction')),
                ('converted', models.BooleanField(default=False, help_text='User completed registration')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('page_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='tournaments.pageview')),
            ],
            options={
                'db_table': 'analytics_user_engagement',
                'ordering': ['-session_start'],
            },
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_type', '-created_at'], name='analytics_p_page_ty_c3ad6d_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', '-created_at'], name='analytics_p_user_id_76d78e_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_key', '-created_at'], name='analytics_p_session_19f8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['is_mobile', '-created_at'], name='analytics_p_is_mobi_59bf52_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_type', '-created_at'], name='analytics_e_error_t_8a3b17_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['severity', '-created_at'], name='analytics_e_severit_9c7128_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['is_resolved', '-created_at'], name='analytics_e_is_reso_2e9dee_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['url', '-created_at'], name='analytics_e_url_e0ac1b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['event_type', '-created_at'], name='analytics_c_event_t_bb1776_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['content_type', 'object_id'], name='analytics_c_content_a7a646_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['user', '-created_at'], name='analytics_c_user_id_c274f4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['session_key', '-created_at'], name='analytics_c_session_bd01dd_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['metric_type', 'metric_name', '-created_at'], name='analytics_p_metric__d18d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['page_view', 'metric_name'], name='analytics_p_page_vi_345013_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['is_mobile', '-created_at'], name='analytics_p_is_mobi_f0f1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['converted', '-session_start'], name='analytics_u_convert_31e26b_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['bounced', '-session_start'], name='analytics_u_bounced_e53b48_idx'),
        ),
    ]
