# Generated by Django 5.2.8 on 2026-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_add_analytics_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='standings_cache',
            field=models.JSONField(blank=True, help_text='Cached standings for RR/Swiss brackets', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_letter',
            field=models.CharField(blank=True, default='', help_text='Alphabetical ID (A, B, C..., GF, GF2)', max_length=4),
        ),
    ]
