# Generated by Django 5.2.8 on 2026-06-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_two_factor_grace_started_at'),
        ('tournaments', '0011_fgc_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='characters/portraits/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='characters/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on character select')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.game')),
            ],
            options={
                'db_table': 'fgc_characters',
                'ordering': ['game', 'order', 'name'],
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FGCGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_best_of', models.IntegerField(default=3, help_text='Default best-of rounds (3 or 5)')),
                ('supports_character_select', models.BooleanField(default=True)),
                ('supports_stage_select', models.BooleanField(default=True)),
                ('max_players_per_match', models.IntegerField(default=2)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fgc_details', to='core.game')),
            ],
            options={
                'verbose_name': 'FGC Game',
                'verbose_name_plural': 'FGC Games',
                'db_table': 'fgc_games',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stages/')),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.game')),
            ],
            options={
                'db_table': 'fgc_stages',
                'ordering': ['game', 'name'],
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GameSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(help_text='Game number within the set (1-5 for Bo5)')),
                ('character_p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_p1', to='tournaments.character')),
                ('character_p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_p2', to='tournaments.character')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_slots', to='tournaments.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_wins', to='tournaments.participant')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.stage')),
            ],
            options={
                'db_table': 'match_game_slots',
                'ordering': ['match', 'slot_number'],
                'unique_together': {('match', 'slot_number')},
            },
        ),
    ]
