# Generated by opencode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_populate_fgc_data_t8_strive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='playoffs_format',
            field=models.CharField(blank=True, choices=[('single_elim', 'Single Elimination'), ('double_elim', 'Double Elimination'), ('swiss', 'Swiss System'), ('round_robin', 'Round Robin'), ('group_stage', 'Group Stage + Playoffs')], default='double_elim', help_text='Bracket format for playoffs after group stage', max_length=20),
        ),
    ]
