# Generated by Django 5.2.8 on 2025-11-24 10:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coach_availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CoachGameExpertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('challenger', 'Challenger/Pro')], max_length=20)),
                ('rank_proof', models.URLField(blank=True, help_text='Link to profile/stats')),
                ('specialization_notes', models.TextField(blank=True)),
                ('custom_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override default rate for this game', max_digits=8, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coach_game_expertise',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='CoachingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_sessions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('session_duration', models.IntegerField(help_text='Minutes per session')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_for_days', models.IntegerField(default=90, help_text='Days to use package')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coaching_packages',
                'ordering': ['coach', 'total_price'],
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('topics', models.JSONField(blank=True, default=list, help_text='e.g., ["Lane control", "Combos", "Game sense"]')),
                ('student_notes', models.TextField(blank=True, help_text="Student's goals for session")),
                ('coach_notes', models.TextField(blank=True, help_text="Coach's session notes")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_intent_id', models.CharField(blank=True, help_text='Stripe payment ID', max_length=200)),
                ('video_link', models.URLField(blank=True, help_text='Meeting link')),
                ('recording_link', models.URLField(blank=True, help_text='Optional session recording')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coaching_sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(help_text='Tell students about yourself')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='e.g., ["Character coaching", "Strategy", "Mechanics"]')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner Coach'), ('intermediate', 'Intermediate Coach'), ('advanced', 'Advanced Coach'), ('professional', 'Professional/Pro Player'), ('world_class', 'World Class')], default='intermediate', max_length=20)),
                ('years_experience', models.IntegerField(default=0)),
                ('achievements', models.TextField(blank=True, help_text='Tournament wins, rankings, etc.')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_break', 'On Break')], default='active', max_length=20)),
                ('accepting_students', models.BooleanField(default=True)),
                ('max_students_per_week', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_session_duration', models.IntegerField(default=60, help_text='Minutes')),
                ('max_session_duration', models.IntegerField(default=180, help_text='Minutes')),
                ('session_increment', models.IntegerField(default=30, help_text='Booking increment in minutes')),
                ('offers_individual', models.BooleanField(default=True)),
                ('offers_group', models.BooleanField(default=False)),
                ('max_group_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('preferred_platform', models.CharField(default='Discord', help_text='Discord, Zoom, etc.', max_length=50)),
                ('platform_username', models.CharField(blank=True, max_length=100)),
                ('profile_video', models.URLField(blank=True, help_text='YouTube/Twitch intro video')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coach_profiles',
                'ordering': ['-average_rating', '-total_sessions'],
            },
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessions_remaining', models.IntegerField()),
                ('sessions_used', models.IntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'package_purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('knowledge_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('patience_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('review', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('improvement_seen', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('coach_response', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
