# Generated by Django 5.2.8 on 2025-11-24 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachgameexpertise',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
        migrations.AddField(
            model_name='coachingpackage',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='additional_students',
            field=models.ManyToManyField(blank=True, related_name='group_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.game'),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coaching.coachprofile'),
        ),
        migrations.AddField(
            model_name='coachingpackage',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='coaching.coachprofile'),
        ),
        migrations.AddField(
            model_name='coachgameexpertise',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_expertise', to='coaching.coachprofile'),
        ),
        migrations.AddField(
            model_name='coachavailability',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='coaching.coachprofile'),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coaching.coachingpackage'),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionreview',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coaching.coachprofile'),
        ),
        migrations.AddField(
            model_name='sessionreview',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='coaching.coachingsession'),
        ),
        migrations.AddField(
            model_name='sessionreview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coachingsession',
            index=models.Index(fields=['coach', 'status'], name='coaching_se_coach_i_678f42_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingsession',
            index=models.Index(fields=['student', 'status'], name='coaching_se_student_2f4218_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingsession',
            index=models.Index(fields=['scheduled_start'], name='coaching_se_schedul_5cd42d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coachgameexpertise',
            unique_together={('coach', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='coachavailability',
            unique_together={('coach', 'weekday', 'start_time')},
        ),
    ]
