# Generated by Django 5.2.8 on 2025-12-07 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('tournament', 'Tournament'), ('team', 'Team'), ('social', 'Social'), ('platform', 'Platform')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('icon_url', models.URLField(blank=True)),
                ('is_progressive', models.BooleanField(default=False)),
                ('target_value', models.IntegerField(default=1)),
                ('points_reward', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'achievements',
                'ordering': ['achievement_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('tournament_registered', 'Tournament Registered'), ('tournament_completed', 'Tournament Completed'), ('team_joined', 'Team Joined'), ('team_left', 'Team Left'), ('achievement_earned', 'Achievement Earned'), ('payment_completed', 'Payment Completed'), ('profile_updated', 'Profile Updated'), ('friend_added', 'Friend Added'), ('game_profile_added', 'Game Profile Added')], max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activities_user_id_7bdf29_idx'), models.Index(fields=['activity_type', '-created_at'], name='activities_activit_b6cd50_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('tournament', 'Tournament'), ('team', 'Team')], max_length=20)),
                ('object_id', models.UUIDField()),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=200)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'recommendation_type', '-score'], name='recommendat_user_id_8bfde1_idx'), models.Index(fields=['user', 'is_dismissed'], name='recommendat_user_id_dda46a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_value', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('in_showcase', models.BooleanField(default=False)),
                ('showcase_order', models.IntegerField(default=0)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='dashboard.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='user_achiev_user_id_171932_idx'), models.Index(fields=['user', 'in_showcase', 'showcase_order'], name='user_achiev_user_id_f9f931_idx')],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
