# Generated by Django 5.2.8 on 2025-12-08 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCompleteness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('max_points', models.IntegerField(default=100)),
                ('percentage', models.IntegerField(default=0)),
                ('completed_fields', models.JSONField(default=dict)),
                ('incomplete_fields', models.JSONField(default=list)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completeness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Completeness',
                'verbose_name_plural': 'Profile Completeness',
                'db_table': 'profile_completeness',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('inappropriate_content', 'Inappropriate Username or Avatar'), ('harassment', 'Harassment or Abusive Behavior'), ('spam', 'Spam or Advertising'), ('cheating', 'Cheating or Unfair Play'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'db_table': 'user_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reported_user', 'status'], name='user_report_reporte_c311b8_idx'), models.Index(fields=['status', '-created_at'], name='user_report_status_219f15_idx')],
            },
        ),
    ]
