# Generated by Django 5.2.8 on 2026-06-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('reason', models.TextField(help_text='Why do you want to become an organizer?')),
                ('experience', models.TextField(blank=True, help_text='Previous tournament or event organization experience')),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to the user if rejected')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizer Application',
                'verbose_name_plural': 'Organizer Applications',
                'db_table': 'organizer_applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='organizer_a_status_5158d5_idx'), models.Index(fields=['user', 'status'], name='organizer_a_user_id_91df5a_idx')],
            },
        ),
    ]
