"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config, Csv
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-)6&8w(h5*v(y-#3b11*j%5%*c%z^2iz1(lu7d+^ru@(7l@_n%3')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Silence django-ratelimit cache warnings in development
# In production, use Redis which is fully supported
if DEBUG:
    SILENCED_SYSTEM_CHECKS = [
        'django_ratelimit.E003',  # Cache backend doesn't support atomic increment
        'django_ratelimit.W001',  # Cache backend not officially supported
    ]

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,8da9-102-89-32-49.ngrok-free.app', cast=Csv())

# Site URL for email notifications and absolute URLs
# In production, set this in your .env file: SITE_URL=https://yourdomain.com
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000' if DEBUG else '')

# Add ngrok support for testing
if DEBUG:
    # Allow all ngrok domains in development
    ALLOWED_HOSTS += ['.ngrok-free.app', '.ngrok.io', '.ngrok.app', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',


    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid',
    'allauth.socialaccount.providers.discord',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.steam',
    'crispy_forms',
    'crispy_tailwind',
    'widget_tweaks',
    'rest_framework',
    'corsheaders',
    'django_htmx',
    'django_extensions',
    'guardian',
    'tailwind',
    'django_browser_reload',
    'django_celery_beat',
    'django_celery_results',
    'django_ratelimit',



     # Local apps
    'core.apps.CoreConfig',
    'security.apps.SecurityConfig',
    'accounts.apps.AccountsConfig',
    'tournaments.apps.TournamentsConfig',
    'teams.apps.TeamsConfig',
    'coaching.apps.CoachingConfig',
    'venues.apps.VenuesConfig',
    'payments.apps.PaymentsConfig',
    'notifications.apps.NotificationsConfig',
    'dashboard.apps.DashboardConfig',
    'store.apps.StoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Custom security middleware
    'security.middleware.SecurityHeadersMiddleware',
    'security.middleware.AuditLogMiddleware',
    # Store rate limiting middleware
    'store.middleware.RateLimitMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.site_settings',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"postgresql://{config('DB_USER', default='postgres')}:"
                f"{config('DB_PASSWORD', default='postgres')}@"
                f"{config('DB_HOST', default='localhost')}:"
                f"{config('DB_PORT', default='5432')}/"
                f"{config('DB_NAME', default='eytgaming_db')}",
        conn_max_age=600
    )
}


# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')
TIME_ZONE = config('TIME_ZONE', default='UTC')
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sites framework
SITE_ID = 1


# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
]

# Django-allauth settings (updated for latest version)
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_PROVIDERS = {
    'discord': {
        'SCOPE': ['identify', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'steam': {
        'KEY': config('STEAM_API_KEY', default=''),
    }
}

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'tailwind'
CRISPY_TEMPLATE_PACK = 'tailwind'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS settings
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000', cast=Csv())

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/1')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Cache
# Use Redis in production, fallback to database cache in development
# Cache Configuration
# django-ratelimit requires a shared cache backend with atomic increment support
if DEBUG:
    # Development: Use database cache (works without Redis, supports atomic operations)
    # Run: python manage.py createcachetable to create the cache table
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }
else:
    # Production: Use Redis cache
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://localhost:6379/0'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'eytgaming',
            'TIMEOUT': 300,  # 5 minutes default timeout
        }
    }

# Session
# Use database sessions for reliability (works without Redis)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@eytgaming.com')

# Stripe
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# CSRF Trusted Origins (for ngrok and production)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000', cast=Csv())

# Add ngrok support for testing in development
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'https://*.ngrok-free.app',
        'https://*.ngrok.io',
        'https://*.ngrok.app',
    ]

# Security Settings (Production)
if not DEBUG:
    # HTTPS enforcement
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # XSS and content type protection
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # X-Frame-Options
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development: keep defaults but still enable basic security flags
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
# Sentry - only initialize if DSN is provided and not a placeholder
    sentry_dsn = config('SENTRY_DSN', default=None)
    if sentry_dsn and sentry_dsn != 'your_sentry_dsn' and sentry_dsn.startswith('https://'):
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        
        sentry_sdk.init(
            dsn=sentry_dsn,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.1,
            send_default_pii=False,
        )

# Django Debug Toolbar (Development only)
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1', 'localhost']

# Tailwind CSS
TAILWIND_APP_NAME = 'frontend'
NPM_BIN_PATH = config('NPM_BIN_PATH', default='/usr/local/bin/npm')

# Custom Settings
TOURNAMENT_CHECK_IN_WINDOW = 30  # minutes before start
MAX_TEAM_SIZE = 10
MIN_TOURNAMENT_PARTICIPANTS = 4
COACHING_SESSION_DURATION = 60  # minutes
POINTS_PER_WIN = 100
POINTS_PER_LOSS = 25

# ==============================================================================
# SOCIAL MEDIA URLS (for landing page)
# ==============================================================================

DISCORD_URL = config('DISCORD_URL', default='https://discord.gg/eytgaming')
TWITTER_URL = config('TWITTER_URL', default='https://twitter.com/eytgaming')
TWITCH_URL = config('TWITCH_URL', default='https://twitch.tv/eytgaming')
YOUTUBE_URL = config('YOUTUBE_URL', default='https://youtube.com/@eytgaming')


# ==============================================================================
# STRIPE PAYMENT CONFIGURATION
# ==============================================================================

STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# ==============================================================================
# Paystack Payment Configuration
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', '')
PAYSTACK_WEBHOOK_SECRET = config('PAYSTACK_WEBHOOK_SECRET', '')
# ==============================================================================


# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@eytgaming.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='server@eytgaming.com')

# ==============================================================================
# NOTIFICATION SETTINGS
# ==============================================================================

# Maximum notifications to keep per user
MAX_NOTIFICATIONS_PER_USER = 1000

# Notification expiry (days)
NOTIFICATION_EXPIRY_DAYS = 90

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# Maximum failed login attempts before account lock
MAX_LOGIN_ATTEMPTS = 5

# Account lock duration (seconds)
ACCOUNT_LOCK_DURATION = 3600  # 1 hour

# Rate limiting
RATE_LIMIT_ENABLED = config('RATE_LIMIT_ENABLED', default=True, cast=bool)

# Session security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# ==============================================================================
# CELERY CONFIGURATION (for background tasks)
# ==============================================================================

# Celery settings (uncomment when ready to use)
# CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================

import sys

# Determine if we're on Windows
IS_WINDOWS = sys.platform.startswith('win')

# Build handler configurations based on platform
if IS_WINDOWS:
    # Windows: Use RotatingFileHandler (size-based rotation)
    file_handler_config = {
        'level': 'INFO',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'django.log',
        'maxBytes': 10485760,  # 10MB
        'backupCount': 10,
        'formatter': 'verbose',
    }
    security_handler_config = {
        'level': 'INFO',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'security.log',
        'maxBytes': 10485760,  # 10MB
        'backupCount': 10,
        'formatter': 'security',
    }
else:
    # Unix/Linux: Use TimedRotatingFileHandler (time-based rotation)
    file_handler_config = {
        'level': 'INFO',
        'class': 'logging.handlers.TimedRotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'django.log',
        'when': 'midnight',
        'interval': 1,
        'backupCount': 10,
        'formatter': 'verbose',
    }
    security_handler_config = {
        'level': 'INFO',
        'class': 'logging.handlers.TimedRotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'security.log',
        'when': 'midnight',
        'interval': 1,
        'backupCount': 10,
        'formatter': 'security',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} [{levelname}] {module} - {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': file_handler_config,
        'security_file': security_handler_config,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ==============================================================================
# RATE LIMITING CONFIGURATION
# ==============================================================================

# Django Rate Limit Settings
RATELIMIT_ENABLE = config('RATELIMIT_ENABLE', default=True, cast=bool)
RATELIMIT_USE_CACHE = 'default'  # Use default cache for rate limiting

# Rate limit view - custom view for rate limit exceeded
RATELIMIT_VIEW = 'payments.views.rate_limit_exceeded'

# Rate limiting uses the default cache backend


# ==============================================================================
# STORE SECURITY CONFIGURATION
# ==============================================================================

# Store-specific security settings
STORE_RATE_LIMIT_ENABLED = config('STORE_RATE_LIMIT_ENABLED', default=True, cast=bool)

# Session security for store checkout
# Ensure sessions are secure and HTTPOnly
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF protection for store forms
# Note: CSRF_COOKIE_HTTPONLY should be False to allow JavaScript access for AJAX requests
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token for AJAX
CSRF_COOKIE_SAMESITE = 'Lax'  # Prevent CSRF attacks via cross-site requests
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens for better performance
CSRF_COOKIE_NAME = 'csrftoken'  # Standard cookie name
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'  # Header name for AJAX requests
CSRF_FAILURE_VIEW = 'store.views.csrf_failure'  # Custom CSRF failure view

# HTTPS enforcement in production
if not DEBUG:
    # Force HTTPS for all store pages
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Additional security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Store logging configuration
LOGGING['loggers']['store'] = {
    'handlers': ['console', 'security_file'],
    'level': 'INFO',
    'propagate': False,
}

# ==============================================================================
# STORE BUSINESS CONFIGURATION
# ==============================================================================

# Cart settings
CART_SESSION_ID = 'cart'
CART_EXPIRY_DAYS = 30  # Days to keep cart for authenticated users

# Order settings
ORDER_NUMBER_PREFIX = 'EYT'

# Inventory settings
LOW_STOCK_THRESHOLD = 10  # Show warning when stock is below this

# Payment settings (Stripe and Paystack already configured above)
# Additional store-specific payment settings can be added here
