# Generated by Django 5.2.3 on 2026-06-03 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0015_add_playoffs_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Provider name (e.g. start.gg, PandaScore)', max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='API base URL')),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key / personal access token')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_min', models.IntegerField(default=60, help_text='Max requests per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_providers',
            },
        ),
        migrations.CreateModel(
            name='ExternalTournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text="Provider's tournament ID", max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('game', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_references', to='tournaments.tournament')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='integrations.externalprovider')),
            ],
            options={
                'db_table': 'external_tournaments',
            },
        ),
        migrations.CreateModel(
            name='ExternalMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=200)),
                ('round', models.IntegerField(default=1)),
                ('players', models.JSONField(default=list, help_text='List of player external_ids or usernames')),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='integrations.externalprovider')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='integrations.externaltournament')),
            ],
            options={
                'db_table': 'external_matches',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('tournament', 'Tournament Sync'), ('player', 'Player Sync'), ('standings', 'Standings Sync'), ('discovery', 'Tournament Discovery')], max_length=20)),
                ('status', models.CharField(default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('items_processed', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.externalprovider')),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('game', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.URLField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Provider-specific stats (rank, win rate, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_profiles', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='integrations.externalprovider')),
            ],
            options={
                'db_table': 'external_players',
                'indexes': [models.Index(fields=['provider', 'game'], name='external_pl_provide_d5198a_idx')],
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.AddIndex(
            model_name='externaltournament',
            index=models.Index(fields=['provider', 'status'], name='external_to_provide_f25351_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externaltournament',
            unique_together={('provider', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='externalmatch',
            unique_together={('provider', 'external_id')},
        ),
    ]
