# Generated by Django 5.2.3 on 2026-06-14 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'db_table': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Deal name/title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Total deal value in USD', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, help_text='Specific terms and deliverables')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(limit_choices_to={'is_verified_personality': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_deals', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='sponsorships.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsorship Deal',
                'verbose_name_plural': 'Sponsorship Deals',
                'db_table': 'sponsorship_deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['celebrity', 'status'], name='sponsorship_celebri_5a6a1d_idx'), models.Index(fields=['sponsor', 'status'], name='sponsorship_sponsor_bd094f_idx')],
            },
        ),
    ]
