# Generated by Django 5.2.8 on 2025-11-24 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template identifier', max_length=100, unique=True)),
                ('notification_type', models.CharField(help_text='Type of notification this template is for', max_length=20)),
                ('title_template', models.CharField(help_text="Title template with placeholders (e.g., 'New message from {sender}')", max_length=200)),
                ('message_template', models.TextField(help_text='Message template with placeholders')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('default_delivery_methods', models.JSONField(default=list, help_text='Default delivery methods for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_tournament_updates', models.BooleanField(default=True)),
                ('email_coaching_reminders', models.BooleanField(default=True)),
                ('email_team_activity', models.BooleanField(default=True)),
                ('email_payment_receipts', models.BooleanField(default=True)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('push_tournament_updates', models.BooleanField(default=True)),
                ('push_coaching_reminders', models.BooleanField(default=True)),
                ('push_team_activity', models.BooleanField(default=True)),
                ('push_match_updates', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_urgent_only', models.BooleanField(default=True)),
                ('discord_enabled', models.BooleanField(default=False)),
                ('discord_webhook_url', models.URLField(blank=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('tournament', 'Tournament Update'), ('coaching', 'Coaching Session'), ('team', 'Team Activity'), ('payment', 'Payment'), ('system', 'System Notification'), ('security', 'Security Alert'), ('venue', 'Venue Booking'), ('match', 'Match Update'), ('message', 'Direct Message'), ('achievement', 'Achievement Unlocked')], help_text='Type of notification', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('delivery_methods', models.JSONField(default=list, help_text="List of delivery methods used (e.g., ['in_app', 'email'])")),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_cba35e_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_498289_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_b3d0b6_idx')],
            },
        ),
    ]
